name: google_drive_realtime
version: 0.0.3-dev
author: Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
description: With that package you will be able to use Google Drive Realtime API from Dart scripts.
homepage: https://github.com/a14n/dart-google-drive-realtime
dependencies:
  js: '>=0.0.20 <1.0.0'
  hop: any
dev_dependencies:
  unittest: any
  browser: any
  meta: any
